apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: php-deploy
  template:
    metadata:
      labels:
        app: php-deploy
