apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 503237308475.dkr.ecr.eu-west-3.amazonaws.com/team4php
  newName: 503237308475.dkr.ecr.eu-west-3.amazonaws.com/team4php
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- deploy-patch.yaml
- service-patch.yaml
