---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: team4php
  region: eu-west-3
fargateProfiles:
  - name: fr-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: fr-fargate
